version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: p4ssw0rd
    volumes:
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8100:5432"

  server:
    build: ./server
    ports:
      - "8000:5000"
    environment:
      DATABASE_URL: postgres://user:p4ssw0rd@db:5432/postgres
      DATABASE_NAME: postgres
      DATABASE_USER: user
      DATABASE_PASSWORD: p4ssw0rd
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      AUTH_SECRET: thisisasecret
      AUTH_DOMAIN: localhost
      PORT: 3000
      FLASK_DEBUG: True
    depends_on:
      - db

  web:
    build:
      context: web
      target: development
    ports:
      - 8200:3000
    volumes:
      - ./web/:/app:cached
      - /app/node_modules

